name: Scheduled - ACR Onboarding

on:
  workflow_dispatch:  # Triggered manually via GitHub UI  
  schedule:
    - cron: '0 6 * * 1'  # At 06:00 on Monday

env:
  PRISMA_API_URL: ${{ secrets.PRISMA_API_URL }}
  PRISMA_ACCESS_KEY: ${{ secrets.PRISMA_ACCESS_KEY }}
  PRISMA_SECRET_KEY: ${{ secrets.PRISMA_SECRET_KEY }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  acr_onboarding:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py script
        run: |
          python acr_automatic_onboarding.py --force-onboard
